# -*- coding: utf-8 -*-
"""download_instagram_post

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ozh5z6l16w5ZrplWafQYh3Jn_pepsi5n
"""

pip install instabot

from instabot import Bot

bot = Bot ()
bot.login(username = "user_name",
          password = "user_password")

bot.upload_photo("YourPost.jpg",
                 caption = "caption of Post Here")